version: 2

jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/python:3.7.2

    steps:
      - checkout
      - run: sudo apt install swig
      - restore_cache:
          keys:
            - build-{{checksum "requirements.txt"}}
      - run: python3 -m venv ~/venv
      - run: |
          source ~/venv/bin/activate
          pip install --upgrade pip
          pip install --upgrade pylint
          pip install -r requirements.txt
      - save_cache:
          key: build-{{checksum "requirements.txt"}}
          paths:
            - ~/venv
      - run: echo 'export PYTHONPATH=~/repo' >> $BASH_ENV
      - run: |
          source ~/venv/bin/activate
          flake8
      - run: |
          source ~/venv/bin/activate
          pytest -m "not gpu"
      - run: |
          source ~/venv/bin/activate
          ls -1 */__init__.py | sed -E 's|/.*||' | xargs pylint -r n
workflows:
  version: 2

  build:
    jobs:
      - build
